### ISSUE TITLE
Out of sync!

### ISSUE THREAD

**Issue by GunLab91** [PXN-Foundation/Peepcoin#16]
...
trying connection 89.77.45.8:8193 lastseen=408693.2hrs
connection timeout
trying connection 94.255.128.181:8193 lastseen=408693.2hrs
connection timeout
trying connection 95.135.148.57:8193 lastseen=408693.2hrs
connection timeout
trying connection 95.174.107.132:8193 lastseen=408693.2hrs
connection timeout
trying connection 99.238.98.144:8193 lastseen=408693.2hrs
connection timeout
trying connection 103.53.200.206:8193 lastseen=408693.2hrs
connection timeout
trying connection 72.189.84.32:8193 lastseen=408693.2hrs
connection timeout
trying connection 92.188.69.232:8193 lastseen=408693.2hrs
connection timeout
trying connection 99.31.212.76:8193 lastseen=408693.2hrs
connection timeout
...

I use peepcoin wallet v1.0.4 windows 64 bit

Please advise.

Thanks

**Comment by sibcool** [comment]
Go to the explorer site - https://chainz.cryptoid.info/pcn/#!network
Click on nodelist for /PXN:1.0.4.1/ and change the addnodes in your peepcoin.conf file to list you get from the site.

**Comment by sibcool** [comment]
Also please get wallet 1.0.4.1 - at least.  But we will be releasing 1.0.5.0 soon.
